# Heads textures are always in base64
# where heads materials are possible if the string does not correspond to a bas64 head or a Bukkit Material then defaulted to BARRIER

force-legacy-material-load-at-enable: true
gui:
  main: # all items in the gui
    title: ""
    rows: 4
    quick-arenas:
      enabled: true
      refresh: # refresh the quick plays arenas when the player has the main inventory open
        enabled: true
        delay: 40 # in ticks
      start-slot: 12
      slots-count: 5
      # theses can be heads
      show:
        full: false
        waiting: true
        starting: true
        restarting: false
        playing: false
      material-waiting: "YELLOW_STAINED_GLASS"
      material-starting: "LIME_STAINED_GLASS"
      material-playing: "LIGHT_BLUE_STAINED_GLASS"
      material-restarting: "BLUE_STAINED_GLASS"
      material-no-arena: "BARRIER"
    rejoin:
      enabled: true
      slot: 35
      material-available: "ENDER_PEARL" # can be head TEXTURE
      material-unavailable: "BARRIER" # can be head texture
    quick-join:
      enabled: true
      slot: 10
      material: "NETHER_STAR" # can be head TEXTURE
    categories:
      enabled: true
      slot: 27
      material: "CHEST" # can be head TEXTURE
    hotbar-manager:
      enabled: true
      slot: 28
      material: "BLAZE_ROD" # can be head TEXTURE
    quick-buy:
      enabled: false
      slot: 29
      material: "EMERALD" # can be head TEXTURE
  map-selector:
    rows: 6
    back:
      enabled: true
      slot: 49
      material: "ARROW"
    map:
      slots: [10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43]
  category:
    rows: 6
    categories:
      2v8:







# Old things lol
bw-categories-menu:
  menu-rows: 6
  title: "Select a category"
  categories:
    1x8:
      slot: 10
      item-material: ""
      item-amount: 1
      item-name: ""
      item-lore:
        - ""
        - ""
      item-glow: true # enhancement glow
    2x8:
      slot: 11
      item-material: ""
      item-amount: 1
      item-name: ""
      item-lore:
        - ""
        - ""
      item-glow: true # enhancement glow
    armed-2x4:
      fancy-name: "Armed 2x4"
      slot: 28
      item-material: ""
      item-amount: 1
      item-name: ""
      item-lore:
        - ""
        - ""
      item-glow: true # enhancement glow